remove [[nodiscard]] as it is a C++17 feature
VisualC complains with:

```
d:\a\morphio\morphio\3rdparty\lexertl14\include\lexertl\rules.hpp(505): error C2429: attribute 'nodiscard' requires compiler flag '/std:c++17'
  d:\a\morphio\morphio\3rdparty\lexertl14\include\lexertl\rules.hpp(1312): note: see reference to class template instantiation 'lexertl::basic_rules<r_ch_type,ch_type,id_ty>' being compiled
```